### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by domohuhn** [domohuhn/mutation-test#15]
The tests currently do not run code in several files (and codecov doesnot see them either):

- html_reporter.dart
- mutation_progress_bar.dart
- mutation_test.dart
- report_format.dart
- test_runnner.dart

**Comment by domohuhn** [comment]
More tests are visible. If the coverage should be increased, refactoring has to be done: Each interaction with the system should be behind an abstraction (writing files, executing a test command). Then, the test coverage can be improved.

**Comment by domohuhn** [comment]
Refacotrin is done and all files are visible now in codecov.

**Comment by NassimMaluli** [comment]
Specifying (flutter test test/some_test_file.dart) as command in the input files (ex: config.xml) is throwing the following Error / Exception :
"Error while processing:
  ProcessException: Das System kann die angegebene Datei nicht finden.

  Command: flutter test test/example_test.dart"
  
How can this work ?
