### ISSUE TITLE
can't run flutter tests...

### ISSUE THREAD

**Issue by NassimMaluli** [domohuhn/mutation-test#18]
Specifying (flutter test test/some_test_file.dart) as command in the input files (ex: config.xml) is throwing the following Error / Exception :
"Error while processing:
ProcessException: Das System kann die angegebene Datei nicht finden.

Command: flutter test test/example_test.dart"

Are "flutter test" commands not supported ?

**Comment by domohuhn** [comment]
The program spawns a new shell and executes the given command. Any program that you can run via your command line can be used as verification command for the mutation_test binary. 
In your case, the error "Das System kann die angegebene Datei nicht finden." means that the system cannot find a program called flutter in the default search path.
To verify, open a standard shell and type in "flutter --version". You should see the same error.

The most likely fix for you is that you will either have to add the location of the flutter binary to your PATH environment variable or use the full path in the config.xml command, e.g.
"C:\programs\flutter\bin\flutter.bat test test/some_test_file.dart" for windows or the equivalent for other OSs.

**Comment by NassimMaluli** [comment]
Thanks very much :) . Indeed adding the full path to the flutter binary worked.  I had already tried this but messed up the the path to the binary.
