### ISSUE TITLE
`switch function call arguments` rule should not run for named parameters

### ISSUE THREAD

**Issue by marandaneto** [domohuhn/mutation-test#20]
https://github.com/domohuhn/mutation-test/blob/9eff7dee88402e93a0e26fc6941d29fdbc088b0e/lib/src/configuration/builtin_rules.dart#L156C10-L160

Positional and Optional positional parameters may have bugs if misplaced, but I don't see how changing the order of named parameters would help.

**Comment by domohuhn** [comment]
This should be fixed in 26fdb8b
